CREATE TABLE IF NOT EXISTS episode_metrics (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT,
    episode_id VARCHAR(128) NOT NULL,
    reaction_like INT UNSIGNED NOT NULL DEFAULT 0,
    reaction_love INT UNSIGNED NOT NULL DEFAULT 0,
    reaction_care INT UNSIGNED NOT NULL DEFAULT 0,
    reaction_haha INT UNSIGNED NOT NULL DEFAULT 0,
    reaction_wow INT UNSIGNED NOT NULL DEFAULT 0,
    reaction_sad INT UNSIGNED NOT NULL DEFAULT 0,
    reaction_angry INT UNSIGNED NOT NULL DEFAULT 0,
    share_count INT UNSIGNED NOT NULL DEFAULT 0,
    comment_count INT UNSIGNED NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uq_episode_metrics_episode_id (episode_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
